name: future_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  modal_progress_hud_nsn: ^0.5.1
  firebase_database: ^11.1.4
  fl_chart: ^0.71.0
  syncfusion_flutter_charts: ^29.1.38
  intl: ^0.19.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - images/wallepaper.png
   - images/teacher.png
   - images/signphoto.png