// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-mtZx-2Y8mmxppcpaXkbEcXEMVGY6cs',
    appId: '1:417673863804:android:b16a3b1c9e6c7dd49b9ff9',
    messagingSenderId: '417673863804',
    projectId: 'future-app2',
    authDomain: 'future-app2.firebaseapp.com',
    databaseURL: 'https://future-app2-default-rtdb.firebaseio.com/',
    storageBucket: 'future-app2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV-mtZx-2Y8mmxppcpaXkbEcXEMVGY6cs',
    appId: '1:417673863804:android:b16a3b1c9e6c7dd49b9ff9',
    messagingSenderId: '417673863804',
    projectId: 'future-app2',
    databaseURL: 'https://future-app2-default-rtdb.firebaseio.com/',
    storageBucket: 'future-app2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV-mtZx-2Y8mmxppcpaXkbEcXEMVGY6cs',
    appId: '1:417673863804:android:b16a3b1c9e6c7dd49b9ff9',
    messagingSenderId: '417673863804',
    projectId: 'future-app2',
    databaseURL: 'https://future-app2-default-rtdb.firebaseio.com/',
    authDomain: 'future-app2.firebaseapp.com',
    storageBucket: 'future-app2.firebasestorage.app',
  );
}
